### ISSUE TITLE
Convert operating system text and download buttons to dynamic sizing

### ISSUE THREAD

**Issue by WilsonGoins** [ufosc/BytesOfLoveWebsite#14]
The text which displays the operating system option (Mac, Linux, or Windows), as well as the clickable button which says 'Download' are a consistent size no matter what the viewport height and width are. As a result, these elements do not resize when the screen size is changed.

Please change this so that the text size and the size of the buttons are relative to either vh (viewport height) or vw (viewport width). 

This change will likely be implemented by the creation and assignment of CSS classes to these elements. These changes needs to be made in Home.js and Download.js.

**Comment by vyiirus11** [comment]
May I work on this issue

**Comment by WilsonGoins** [comment]
> May I work on this issue

Sorry, unfortunately this issue is already taken by somebody. If you want to collaborate with him and make it better, reach out to @myrtte on Discord.
