### ISSUE TITLE
Add Longer Description to Home

### ISSUE THREAD

**Issue by AntonCSalvador** [ufosc/BytesOfLoveWebsite#16]
Currently nowhere on the website there is a good description of what the game is. We need to add this and make the home page look nicer. You can get the description from the main GitHub repository https://github.com/ufosc/VisualNovel

**Comment by AntonCSalvador** [comment]
Hi! It would be on the actual home page, not the css

**Comment by xiaoguo-jia** [comment]
thank you!

**Comment by LemonadeCodeGirl** [comment]
Can I be assigned this issue? Thank you!

**Comment by AntonCSalvador** [comment]
@LemonadeCodeGirl just assigned!

**Comment by LemonadeCodeGirl** [comment]
Done!
