### ISSUE TITLE
Mobile Banner Mobile View

### ISSUE THREAD

**Issue by AntonCSalvador** [ufosc/BytesOfLoveWebsite#17]
Currently the main home page picture looks weirdly distorted on mobile view.

![image](https://github.com/ufosc/BytesOfLoveWebsite/assets/100897060/73f0814d-ea95-4abc-98da-29e2b2a91b14)

If someone could fix the css to change to make it look better on mobile view that would be nice.

**Comment by vule19** [comment]
May I try this one?

**Comment by AntonCSalvador** [comment]
Go for it @vule19
