### ISSUE TITLE
Redesign Nabar

### ISSUE THREAD

**Issue by WilsonGoins** [ufosc/BytesOfLoveWebsite#18]
The Navbar we currently have is functional, but the team agrees it is missing "something".

Redesign the Navbar component so that it still features the Open Source Club logo and clickable links to the 3 different pages.

This should be done by changing Navbar.js and Navbar.css.

**Comment by xiaoguo-jia** [comment]
can i have this issue? thank you!

**Comment by WilsonGoins** [comment]
> can i have this issue? thank you!

Yes you can work on it, but someone already reached out to me and said they might be interested. Please collaborate with them. Their GitHub is: https://github.com/vyiirus11   I will follow up with their discord soon

**Comment by xiaoguo-jia** [comment]
ok thank you!

**Comment by vyiirus11** [comment]
Yes, I was interested in doing this issue. My discord is @dlenlen1228 if you need to reach out about it.

**Comment by xiaoguo-jia** [comment]
@WilsonGoins What is the best way to get my changes approved to be pushed to the main branch? Would I be able to push my changes to the main branch, and then have @vyiirus11 add on top of it? I have contacted her on discord, and she agreed to this. Thank you!

**Comment by WilsonGoins** [comment]
@xiaoguo-jia @vyiirus11 I would say try to combine your changes together so that you guys can agree on one thing. Then make a PR that has your combined change. As far as making the PR we usually fork the repository and then compare the main branches so when you make your PR make it across repositories.

**Comment by AntonCSalvador** [comment]
@xiaoguo-jia @vyiirus11 I merged this but can you fix the navbar mobile view. When the user goes to mobile the navbar 
![Screenshot at 2024-06-21 14-48-32](https://github.com/ufosc/BytesOfLoveWebsite/assets/100897060/35d10967-7007-4ccd-9e2c-a3f095fc29c5)
it looks a little scuffed with the bytes of love logo. 
Possible solutions are:
- if it gets to that size just get rid of the bytes of love or osc logo
- hamburger menu for when it gets to a certain size
