### ISSUE TITLE
About Page Mobile View

### ISSUE THREAD

**Issue by AntonCSalvador** [ufosc/BytesOfLoveWebsite#20]
**Description:**
The contributor page, titled "About" (found in src/About/About.js) needs improvements to ensure it is fully responsive.

**Tasks:**
1. Ensure the page is more responsive across different screen sizes.
2. Fix the issue where pictures should all stay the same size regardless of the screen size.
3. Address the overflow issue so that all contributors display correctly when resizing the page.

**Testing:**
Please test the responsiveness using Google Chrome's inspect element feature, specifically in mobile view, to ensure everything appears as expected.

**Expected Outcome:**
- The page should look good and function well on all screen sizes.
- Pictures should maintain a consistent size.
- Overflow should be handled properly so that all contributors are displayed correctly without any weird formatting issues.
- Please also test on Firefox if possible

**Example of Error:**
![aboutPage](https://github.com/ufosc/BytesOfLoveWebsite/assets/100897060/e7b0d084-6c3b-40bc-873a-80a391a3bc4b)

Thanks!

**Comment by CarmenvStaden** [comment]
Hi! I would love to try and work on this issue if that's ok, I have cross platform web development experience, usually using react, but I would like to give this a try

**Comment by qiusy99** [comment]
Hi, can I assign to this issue?
