### ISSUE TITLE
Redesign the Download Page

### ISSUE THREAD

**Issue by AntonCSalvador** [ufosc/BytesOfLoveWebsite#25]
# Update Download Page for BytesOfLove Website

## Description
Currently, the Download page only contains "How To Play" and three download links. We need to update this page to provide more information about how the game is run, including details about the engine used (Ren'Py) and other relevant information.

## Current Content
- How To Play
- Link 1
- Link 2
- Link 3

## Proposed Changes
- Include information about the engine used (Ren'Py) and its role in the game.
- Add more content to this page and make it look nice

### Game Engine
BytesOfLove is built using Ren'Py, a popular visual novel engine. Ren'Py allows for rich storytelling experiences through its easy-to-use scripting language and powerful features.

### How to Play
(Existing content about how to play the game)

### Download Links
- [Download for Windows](#)
- [Download for Mac](#)
- [Download for Linux](#)

## Steps to Update
1. Update the Download page content to include the suggested content above.
2. Ensure all links are functional and point to the correct resources.
3. Review the changes with the team before deploying.

## Notes
You can add more description and make the download page look nicer at your own discretion, just keep us in the loop in the bytes-of-website channel in the OSC discord!

**Comment by SeanAverS** [comment]
Hello, 

I am interested on working on this. Could I please be assigned? Thank you.

**Comment by Gursimran07316** [comment]
Hey,

I am interested in working on this. Could you please assign it to me? Thank you.

**Comment by jonana-split** [comment]
Hello, I'm not asking to be assigned just wanted to note for whoever takes on this task that I'm assigned to fixing the download links, and they should be fixed within the next day or so! :D

**Comment by AntonCSalvador** [comment]
@SeanAverS @Gursimran07316 Hi guys so because you both want to do the same issue I would typically give priority to Sean because he asked first but if you guys want to work together on it that is also good. Or if you both want to do it we can work from there. I would still wait for @jonana-split 's edits first though.

**Comment by SeanAverS** [comment]
Hey @Gursimran07316, I submitted a pull request based on the proposed changes. Please let me know if you have any suggestions!

**Comment by AntonCSalvador** [comment]
@SeanAverS I'll review it tonight, I'll let you know if there are any changes needed to be made, thanks for the hard work!
