### ISSUE TITLE
Redesign of Homepage Carousel

### ISSUE THREAD

**Issue by AntonCSalvador** [ufosc/BytesOfLoveWebsite#35]
### Redesign of Homepage Carousel

**Description:**

The current carousel of images on the homepage needs a complete overhaul. We want to update the design to be more modern and less snappy while retaining the existing images. The website is built with React, but if necessary, the redesign can be implemented using basic JavaScript.

**Current Behavior:**
- The carousel is too snappy and lacks a smooth, modern feel.

**Desired Changes:**
- **Design Overhaul:** Redesign the carousel to give it a more contemporary look and feel.
- **Smooth Transition:** Make the transitions between images smoother and less abrupt.
- **Keep Images:** Ensure that all existing images are preserved in the new design.
- **Additional Features:** (Optional) Consider adding modern carousel features such as captions, indicators, or improved navigation.

**Additional Information:**
- Please comment on this thread if you have any questions or want suggestions with the carousel!

**Screenshots:**
- Current carousel: 
![Screenshot at 2024-08-29 14-32-16](https://github.com/user-attachments/assets/82558950-1af9-420f-84f6-c03b214687e6)

**Priority:** Medium

Thank you for addressing this! Looking forward to the updated carousel.

---

**Note:** The website uses React, but if necessary, the carousel redesign can be done using basic JavaScript.

**Comment by PhillipsCorey** [comment]
Hi! Could I take a look at this issue? Thanks!

**Comment by AntonCSalvador** [comment]
@PhillipsCorey assigned!

**Comment by Sky-De** [comment]
@AntonCSalvador @PhillipsCorey hi, do you still work on this issue? Let me know , thanks

**Comment by PhillipsCorey** [comment]
@Sky-De Yes I am, thank you!
